pipelines:
  default:
    - step:
        image:
          hashicorp/terraform:latest
        script:
          - apk add go
          - apk add make
#          - cd terraformprovider
          - make install
          - cd terraformprovider/examples/test
          - ./testall.sh